# Move a new issue into the to do column when assigned

name: Move assigned issues into To do

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Vinilos - Development
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
