name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

# map fields with customized labels
env:
  todo: Todo ✏️
  done: Done ✅
  in_progress: In Progress 🚧

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.VINILOS_SECRET }}
          user: VivianaReyV
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  pr_opened_or_reopened_or_reviewrequested:
      name: pr_opened_or_reopened_or_reviewrequested
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
      steps:
        - id: check-linked-issues
          uses: nearform/github-action-check-linked-issues@v1
          with:
            github-token: '${{ secrets.VINILOS_SECRET }}'
        - name: Get comma-delimited list of found links
          run: echo "${{ steps.check-linked-issues.outputs.linked_issues_count }}}"
        - name: Move PR to ${{ env.in_progress }}
          uses: leonsteinhaeuser/project-beta-automations@v2.0.1
          with:
            gh_token: ${{ secrets.VINILOS_SECRET }}
            user: VivianaReyV
            project_id: 1
            resource_node_id: ${{ github.event.pull_request.node_id }}
            #status_value: ${{ env.in_progress }} # Target status
            
