name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

# map fields with customized labels
env:
  todo: Todo ✏️
  done: Done ✅
  in_progress: In Progress 🚧

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.VINILOS_SECRET }}
          user: VivianaReyV
          project_id: 1
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
      - name: Print
        run: echo "${{ github.event.issue.node_id }}"
  pr_opened_or_reopened_or_reviewrequested:
      name: pr_opened_or_reopened_or_reviewrequested
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
      steps:
        - id: link-issues
          uses: boneskull/more-linked-issues-action@v0.2.1
          with:
            github-token: '${{ secrets.VINILOS_SECRET }}'
        - id: one
          uses: bhowell2/github-substring-action@v1.0.0
          with:
            value: ${{ steps.link-issues.outputs.links }}
            index_of_str: "#"
          # steps.one.outputs.substring = 'c123'
        - uses: monry/actions-get-issue-id@v1
          with:
            # Personal Access Token that with `org:read` are granted.
            github-token: ${{ secrets.VINILOS_SECRET }}
            issue-repository: 'VivianaReyV/misw4203-202215-Vinilos'
            issue-number: ${{ steps.one.outputs.substring }}
        - name: Print
          run: echo "${{ steps.get-project-id.outputs.project-id }}"
        - name: Move PR to ${{ env.in_progress }}
          uses: leonsteinhaeuser/project-beta-automations@v2.0.1
          with:
            gh_token: ${{ secrets.VINILOS_SECRET }}
            user: VivianaReyV
            project_id: 1
            resource_node_id: ${{ steps.one.outputs.substring }}
            status_value: ${{ env.pruebas }} # Target status
            
